### PR TITLE
new spoiler texture

### LINKED ISSUE #100: Airbrake improvement
@D-ECHO please make the airbrakes come out as far as it's shown on page 6 in the manual: https://www.capmembers.com/media/cms/ASK21__Schleicher__Flight_Manual_0F12AEE54A4A2.pdf

The front of the airbrake is painted orange: http://rs231.pbsrc.com/albums/ee247/jetpack_photos/Revell%20Gliders/airbreak_zps1bacd991.jpg~c200

Not sure about the back, I'll try to check next time. Could well be the same colour.

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Closes #100

New spoiler model and texture

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
:warning: :warning: :warning: once again I need some help from @D-ECHO before we can merge this :smile: since the spoiler texture should be the same for all liveries, the more elegant solution is to do the same we did with the wheel: the texture file which is UV-mapped is the default `blank-wings.png` rather than some specific livery. So I pushed a modified `blank-wings.png` with the spoiler exactly where you mapped it, so you just need to direct it to this file. Can you do that?

**Comment by ghost** [comment]
So you just mean that spoilerL and spoilerR are objects not changing with livery?

**Comment by gilbertohasnofb** [comment]
Yes, and that they ~~are~~ should be mapped to `Models\blank-wings.png`. This is the same we did with the wheel. Else we need to fit every livery with the spoiler texture, and they will all be identical, so it wouldn't make sense IMO

**Comment by ghost** [comment]
Looks very very very good!! That's what I like about your texturing: I would have just made it a simple color but with your tex it looks realistic! 
-> Cleared for merge ;)

**Comment by gilbertohasnofb** [comment]
@D-ECHO thanks a lot for the fast fix! It's looking really good :smile: 

> I would have just made it a simple color but with your tex it looks realistic!

Yes, it's always better to have some sort of "grain" or details in the texture, even for solid colours. I have a bunch of public domain texture sources that I use as overlay (metallic ones, scratches, wood, plastic, etc). A good 3D model like in this aircraft with decent textures can result in an amazing final effect :smile:

**Pull request merged**
