### PR TITLE
Improve 57mm compass and turnslip

### PR DESCRIPTION
**Pull request by ghost**
I re-textured them a bit, pls tell whether you like them
@gilbertohasnofb I have included the .xcfs, so if you like you can do some texture-magic there as well, although I don't think there's that much to do here ;)

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@D-ECHO Thanks! I think I can improve it a bit :smile:  I will be free in 1h more or less, so please do not merge it before I push the texture commits

**Comment by gilbertohasnofb** [comment]
@D-ECHO Ok, I am done and I pushed them, see what you think. There are a couple of things you need to take a look at though:

- the bottom screws of both the compass and the turnslip need to be better UV-mapped as the holes are not matching (though it's not very noticiable unless you zoom in). See green arrows in the images below
- please UV-map the turnslip ball to the texture `ball.png` in the same directory, see yellow arrow below
- the "hand" of the turnslip indicator was mapped to the background of the gauge (which previously was solid), and now it doesn't look very nice. Please assign it to the bottom left area of the file `57mm_turnslip.case.png` (see pink arrow and pink rectangle below)

fgfs-screen-001

fgfs-screen-002

image


And by the way, I am getting an error message in the console:

```
Failed to load file: "Aircraft/ASK21/Models/Interior/Panel/Instruments/57mm_turnslip/57mm_screws.xml"
Failed to load file: "Aircraft/ASK21/Models/Interior/Panel/Instruments/57mm_turnslip/57mm_screws.xml"
Failed to load file: "Aircraft/ASK21/Models/Interior/Panel/Instruments/57mm_compass/57mm_screws.xml"
```

**Review by viktorradnai — APPROVED** [review]
Nice :)

**Comment by gilbertohasnofb** [comment]
@viktorradnai oh, you merged this before @D-ECHO made the modifications I asked him to! Not a big deal, but this means that we need another PR for the same issues here, and it's easy to forget what has been asked so maybe we need to also open a new issue for these things

**Comment by gilbertohasnofb** [comment]
@viktorradnai but I am glad you like the result :smile:

**Pull request merged**
