### PR TITLE
Fdm tweaks

### PR DESCRIPTION
**Pull request by viktorradnai**
I had a couple of instructors at my club test-fly the ASK21 and I've made some tweaks to the flight model and the view position based on their feedback.

- raised the view to make the nose look lower in normal flight (before you couldn't see the tug when aerotowing at 60 knots if you allowed its wheels to touch the horizon)
- reduced aileron sensitivity as it was judged to be too high
- increased aileron drag (adverse yaw)
- made the airbrakes more efficient (videos showing 6-8 knots down with airbrake on landing)
- made the wheel brake to kick in on a smaller portion of airbrake travel
- distributed some mass towards the wingtips to give the aircraft more yaw and roll inertia when applying the controls suddenly

### CODE REVIEW

**Comment by ghost** [comment]
Thanks!!! as well here I'll have a look once I'm back from Holidays



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm>


--- Original-Nachricht ---
Von: Viktor Radnai
Betreff: Re: [viktorradnai/flightgear-ask21] Fdm tweaks (#137)
Datum: 22.08.2017, 2:56 Uhr
An: viktorradnai/flightgear-ask21
Cc: D-ECHO, Mention



@viktorradnai <https://github.com/viktorradnai> requested your review on: 
viktorradnai/flightgear-ask21#137
<https://github.com/viktorradnai/flightgear-ask21/pull/137> Fdm tweaks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/viktorradnai/flightgear-ask21/pull/137#event-1215053018> 
, or mute the thread

**Comment by gilbertohasnofb** [comment]
I also can't test for the next days, but this sounds great

> I had a couple of instructors at my club test-fly the ASK21

:+1: :+1: :+1: :+1: :+1:

**Comment by ghost** [comment]
I've just tested your improvements and they seem very realistic to me, so I'll merge this now :D I also got a message from HerbyW telling that he is also working on improvements to the FDM (stall) but has to test it once again.

**Comment by viktorradnai** [comment]
Thanks guys. BTW, my club's instructors tested the aircraft using this: https://www.youtube.com/watch?v=h4afj8YJTMU :D

**Comment by gilbertohasnofb** [comment]
Now this is quite amazing, Viktor! It's looking really spectacular. And by the way, out of curiosity, what is the airclub where you fly in the UK?

**Comment by viktorradnai** [comment]
@gilbertohasnofb Thanks, I fly at the London Gliding Club in Dunstable. If you ever come to the UK, let me know, I might be able to organise a visit. Of course the same offer stands for you as well, @D-ECHO :)

**Comment by gilbertohasnofb** [comment]
@viktorradnai thanks a lot, Viktor! Actually I have just moved to London a couple of days ago as I will be doing my PhD here for the next years, so it could be very nice to organize a visit sometime in the future :smile: but feel absolutely no pressure for it, nor any rush. in these first months I will be super busy with the university

**Comment by ghost** [comment]
@viktorradnai don't plan going to the UK anytime soon, but I've got my gliding club here, maybe one day we can meet and fly? :D (have to finish flight training first though)
Very interested to hear if you two 'll be able to organize a visit

**Pull request merged**
