### PR TITLE
Various bugfixes

### PR DESCRIPTION
**Pull request by colingeniet**
Hello,

This fixes a few issues I found:
- Incorrect nasal imports: nasal files were imported in the same namespace (`ask21`) from both `ask21-main.xml` and the model specific `ask21*-set.xml`. This does not behave as desired, and the latter overrides the former, thus some nasal files were not loaded at all.
- Winch key-bindings did not work in the JSBSim MI variant.
- The battery level display code in `ilec-sc7.nas` was not enabled, and had a couple of small bugs.
- The pitch of the variometer beep did not lower at negative vertical speeds.
I added a bit of nasal code to control the sound frequency. It fixes the issue, somewhat simplifies the xml sound file, and allows better scaling of frequency: frequency now scales exponentially with vertical speed, so that the perceived changes in pitch are linear with vertical speed.
- There was a slight scratch sound in the variometer continuous beep, audible at sufficiently high volume.

### CODE REVIEW

**Comment by D-ECHO** [comment]
Looks good, thank you very much for the fixes!

**Comment by D-ECHO** [comment]
Adding up to this, @colingeniet the new changing pitch in steady tone sounds sooo realistic, thank you so much. It's funny how sometimes such a rather small change can make that big of a difference in perceived realism.

**Comment by colingeniet** [comment]
Thank you very much @D-ECHO 
I would like to port the sound changes (last 2 commits) to FGData to eventually have them in other gliders. Do you have any comments or recommendation before I open a pull request?

**Comment by D-ECHO** [comment]
I had also thought of this, I think that's a good idea. Maybe even include the whole instrument from this repository as it also features an improved texture by @gilbertohasnofb 
@colingeniet

**Pull request merged**
