### PR TITLE
New tail

### PR DESCRIPTION
**Pull request by ghost**
...with better fuselage-tail transition, rudder fix
letters on tail (uvmap) should be fine

I though noticed that with G-CKEJ, the left side competition callsign is a bit far to the rear while it's ok for JWD, maybe we have to change the texture, please check this

### CODE REVIEW

**Review by viktorradnai — CHANGES_REQUESTED** [review]
Looks much better, thanks. There are a couple of minor issues which I'll add as separate comments.

**Comment by viktorradnai** [comment]
Looks good, but there are a couple of things that would be nice to get fixed:

1. The bottom of the rudder should be rounded similarly to the top -- it currently appears squared off.
2. The inside of the fuselage should be textured with a darker material so we can't quite see in like we can now.
fgfs-screen-360

3. There is a dark patch at the end of the bottom of the tail below the rudder cable attachments -- this might be a texturing issue. It's visible on both sides but it's more prominent on the right:

fgfs-screen-355

4. The textures for JWD and KEJ definitely need updating. I couldn't find the appropriate font that was used, it appears to be some condensed variant of Arial. To compensate, I manually stretched the font vertically to make it taller / narrower. Both JWD and KEJ use this kind of font but only JWD has one of the letters printed on the rudder. KEJ has all three letters on the fixed part of the horizontal stabilizer with the rudder completely white.

image

**Comment by ghost** [comment]
I've changed the uvmap to have things more clearly, but unfortunately this leads to all liveries involving letters/numbers on the tail needing to be changed

**Comment by ghost** [comment]
But they'll need to be changed anyways as the ao map changed

**Comment by ghost** [comment]
Okay, took some time but I've now corrected all liveries (hopefully didn't miss any)

**Comment by ghost** [comment]
I think all problems are solved
1. rudder rounded off at the bottom
2. inside darkened
3. Patch not present
4. Liveries fixed
fgfs-screen-758
fgfs-screen-759
fgfs-screen-760
fgfs-screen-761

fgfs-screen-757

**Comment by ghost** [comment]
Are we ready to merge? @viktorradnai

**Review by viktorradnai — APPROVED** [review]

**Comment by viktorradnai** [comment]
Hi, this looks really, really good. Sorry for not picking it up earlier, I've been literally flat out at work the last few weeks and I simply forgot.

**Comment by ghost** [comment]
No problem :D Also had much things to do (school projects, getting ready for the theoretical glider exam)

**Pull request merged**
