### PR TITLE
better black cubemap

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
I have manually tweaked the cubemap on GIMP, added some softness to the borders to make the shadows more realistic and also I "rounded" some of the aircraft features as in a cubemap we are not limited by polygon count. See the effect here:

fgfs-screen-001

### CODE REVIEW

**Comment by viktorradnai** [comment]
This looks great. Although I've always been wondering what exactly that X shaped shadow is. The aircraft has a T-tail :)

**Comment by viktorradnai** [comment]
Also it eventually dawned on me that none of the instruments are affected by the shadow. But that's probably better for the users.

**Comment by gilbertohasnofb** [comment]
@viktorradnai thanks for reviewing and merging this :+1: 

>  Although I've always been wondering what exactly that X shaped shadow is. The aircraft has a T-tail :)

hehe, here is the tail:

fgfs-screen-002

what you see above is because of the angle that the sun is, that is part of the canopy and part of the wing. Try to load the sim in the afternoon and start circling around and you will realize what this cross is :smile:

**Comment by gilbertohasnofb** [comment]
> Also it eventually dawned on me that none of the instruments are affected by the shadow. But that's probably better for the users.

Instruments are quite tricky to get affected by shadows, the c172p has the same issue. There is a solution though which is to place the instruments in their absolute position in the .ac files instead of positioning/offsetting them in the xml, but at least in the c172p nobody has had patience for that yet

**Pull request merged**
