### PR TITLE
Panelstub

### LINKED ISSUE #77: Redo panel uvmap
Gilberto Agostinho contacted me some days ago and offered his help in improving textures. Therefor he suggested to redo the uvmap for the panel so to have it on one texture as it is done for the Interior/parts.png or the interior.png here: https://github.com/D-ECHO/ASW28/blob/master/Models/interior.png
If you are okay with this, I will correct it ;)

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Closes #77 

- improvements to the UV map, particularly for the interior and panel
- new interior and panel textures
- improved liveries

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@D-ECHO @viktorradnai I believe this is ready to be merged

**Comment by ghost** [comment]
From my side it's "clear for merge" :D Will let Viktor look over it as well. Thanks for your great great work @gilbertohasnofb (and  @viktorradnai )

**Comment by gilbertohasnofb** [comment]
@D-ECHO Sounds good to me, so let's wait for @viktorradnai to take a look. And thanks for all the work with the UV mapping and 3D modelling, this cockpit is looking _very_ nice :smile:

**Comment by viktorradnai** [comment]
Hi @gilbertohasnofb, I think the callsigns on the exterior of G-CKEJ and G-JWD ended up worse than they were before. The font colour is too light and the stretching I applied to the markings on the underside of the wing is gone. I also think the reg on the side of the fuselage is a bit too small now, the previous size looked better for me. What was the reason for these changes? Were you trying to make them look more similar to any particular photo(s) on the Internet?

**Comment by viktorradnai** [comment]
@D-ECHO there is a bug with the rear PTT button you just added. It's not animated with the rest of the stick so it stays suspended mid-air when you move the stick around :)

**Comment by viktorradnai** [comment]
BTW, the exterior of the glider stil looks too dark to me when it's in a cloud shadow (it's fine in sunshine). What settings are you guys running Flightgear with? Could you please start at midday with nice fluffy cumulus clouds and take a few screenshots when you are in their shadow?

Also the inside of the cockpit always looks like there is bright sunshine on it which makes the contrast look even worse.

fgfs-screen-238
fgfs-screen-239
fgfs-screen-240
fgfs-screen-241
fgfs-screen-242
fgfs-screen-243
fgfs-screen-244
fgfs-screen-245

**Comment by ghost** [comment]
For the PTT i totally forget will fix this evening, the Problem with shading i have as well but doesn't belong here?

**Comment by gilbertohasnofb** [comment]
@viktorradnai 

> The font colour is too light and the stretching I applied to the markings on the underside of the wing is gone. I also think the reg on the side of the fuselage is a bit too small now, the previous size looked better for me. 

You are right, I have seen some photos now and indeed these could be better. I will take a look at those today and push some improvements, thanks for pointing it out!

**Comment by gilbertohasnofb** [comment]
@viktorradnai I have improved those two liveries, please take a look and see what you think

**Comment by viktorradnai** [comment]
@gilbertohasnofb thanks for this, looks good now. FYI I've actually spent hours one night trying to find photos and tweaking / stretching / positioning the font to look like the couple of photos of the underside that I could find :) Even with that it isn't perfect but it will do until one day I'll get around to visit the winch with my zoom camera and take some pics for documentation purposes. When I go flying I rarely have it on me.

**Comment by viktorradnai** [comment]
Guys, I'll merge this, we can figure out #83 later :)

**Review by viktorradnai — APPROVED** [review]

**Comment by gilbertohasnofb** [comment]
@viktorradnai I have actually changed a little bit the position of the text on the sides as before they were not matching in the position (that is, when comparing the left and right sides, one was higher than the other, and one was a bit further back than the other). But other than that I used the previous livery as reference. As for the bottom of the wings, I did match quite exactly what you came up with before so that should be better now :smile:

**Comment by viktorradnai** [comment]
See this pic for reference:

https://farm5.static.flickr.com/4084/4986357938_69fb9ddc0c_b.jpg

No idea why it was done like this, with the competition ID significantly smaller, maybe so it wouldn't be mistaken with the registration.

**Comment by gilbertohasnofb** [comment]
@viktorradnai I meant the sides of the fuselage, not the left/right wings. That is, the registration on fthe left of the fuselage is now matched in position to the registration in the right. About the wings, I did put them pretty much in the same position as you put before, so I think it should be all good now :smile: 

Great picture, by the way, shows what you are saying very clearly. I wouldn't have imagined they would use it this way

**Comment by viktorradnai** [comment]
Right, thanks, didn't realise they were out of alignment. 

For the underside shot, I was lucky someone took that, I haven't got any just yet.

**Comment by gilbertohasnofb** [comment]
@viktorradnai :smile: :+1:

**Pull request merged**
