### PR TITLE
Bottom panel and placard textures

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Bottom panel and placard textures

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
:warning: :warning: :warning: before merging, I need @D-ECHO to help me out with some things:

- the speedbrake placards are mapped upside down. I could create them upside down in GIMP, but a more elegant solution is to fix this in Blender
- the instructor placard for "open canopy" is different than the pilot. I added it below the seat, please UV-map it
- the instructor seat should also have placard objects for speedbrake, trim and cable release

Could you please do that before we merge this?

**Comment by ghost** [comment]
One moment, but it looks really really good!

**Comment by ghost** [comment]
Cleared to merge from my side ;)

**Comment by gilbertohasnofb** [comment]
@D-ECHO thanks for the fast work! It is looking really good so I am merging this. But later on you might need to reposition the instructor trim placards once you "carve" the trim reference holes, perhaps they should be a little bit to the left? But it doesn't make sense to be trying to improve this now without knowing where the 3D holes in the model will be

**Comment by ghost** [comment]
Yep, I will :D

**Comment by gilbertohasnofb** [comment]
great, many thanks!

**Pull request merged**
