### PR TITLE
Add gui messages for winch speed

### PR DESCRIPTION
**Pull request by ghost**
I've added two messages that show the winch speed when in-/decreasing it, please have a look at it ;)

### CODE REVIEW

**Review by viktorradnai — COMMENTED** [review]
I would rather have the message print out the actual cable speed in meters per second.

**Comment by ghost** [comment]
Is this property correct?
/sim/hitches/winch/winch/max-speed-m-s*/sim/hitches/winch/winch/rel-speed ?

**Comment by ghost** [comment]
Done! Now the absolute winch speed in m/s is shown.

**Comment by ghost** [comment]
Oh, we are going fancy :-D
I will try this later...
THX!

**Comment by viktorradnai** [comment]
Yeah, seems like my comment did not make it last night. I have added cable force as well. Apparently winch drivers observe the slackness of the cable in an attempt to try to keep cable force constant. We can just display the number which makes it easier :)

Also I incremented the back release angle as it was a bit troublesome. It would autorelease on launch if heavier than 0.1kg/m cable was used, and sometimes when pulling up during the initial climb phase of the launch as well. Feels better now.

**Pull request merged**
