### PR TITLE
New interior textures

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
New interior textures as requested by @viktorradnai 

- rubber carpet below each seat
- front of the interior is now yellowish
- changed colour of seats
- removed all xcf files and added them to this repository [here](https://github.com/gilbertohasnofb/ASK21-textures), as to make this repo reasonable small (same thing as we do in the c172p)

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@D-ECHO @viktorradnai see pictures here https://github.com/viktorradnai/flightgear-ask21/pull/98#issuecomment-286762708

and by the way, I added you two as collaborators on the texture repository so we should all have full access to both the aircraft and the texture repo

**Comment by viktorradnai** [comment]
@gilbertohasnofb thanks for this. I have just realised that my big comment about texture improvements which I have replied to #98 has never got posted and it's now lost... Not happy.

Anyway, things I wanted to say:
Have you seen the glider interior pics I've taken at my club and posted here? Some of them might be useful: https://drive.google.com/drive/folders/0BxVWkln4EgdVODV5SXJjRDh5STg

I had some suggestions for texturing changes:
1. I think it would be better to extend the rubber carpet to almost the edge of the painted area. I think our gliders have it that way, and it looks more credible. The floor needs to be curved at the front and flat at the back (so exactly the opposite of how it is now) but I think this would help.
2. The seat cushion would look better if the stripes ended before the edge, to make it look like it had stitches going around it. The cushion is actually removable, not part of the seatpan, it's just being held in place by the insert around the stick. The way it blends in makes it look like it was part of the seat.
3. About the exterior, the shadow around the fuselage where it meets the wing is too dark, and it often looks out of place.
4. The instructor seat should have the same decals applied on the left as the front seat has (for the trim indicator)

In any case I think this is about as much as we can do with the cockpit with texturing, the rest would need some model changes. But I agree with you that the glider is looking really good. In particular when I saw your last screenshot in #98 I thought for a moment that it was a photo.

**Comment by gilbertohasnofb** [comment]
>  I have just realised that my big comment about texture improvements which I have replied to #98 has never got posted and it's now lost... Not happy.

@viktorradnai Ah, no problems! Thanks for making the comments here

> Have you seen the glider interior pics I've taken at my club and posted here?

No I haven't, they are indeed very helpful. I will use them as reference to alter a bit this PR before we merge it. About your comments:

1. :+1: I will extend the rubber carpet until the side walls
2. I don't think I understand you well here, in the images you posted the stitches seem to me to clearly go to the back of the blue cushion. Do you perhaps refer to the grey "contour" around the seat? If so, I can try to add that.
3. Agreed. I actually have already made them a bit lighter, but I will try to improve it still
4. If it's all right with you, let's leave this at it is right now because we will add the trim reference holes to both pilot and instructor as a true 3D hole and I will work on the decals in the future (I also would like to have them as little rectangular 3D objects in order to have enough high resolution, just like the decal for the cockpit opening handle). Is that fine with you?

**Comment by viktorradnai** [comment]
1. I actually meant forward, not sideways. If you do leave a gap, make it roughly the same on the side as on the front.
2. Yes, the grey contour is the stitching where the front and back material is sewn together around the edge. the horizontal stitches are then added to keep the padding from moving around too much and clumping together. I think it would be better to model the shape of the cushion rather than trying to texture the flat pan, but it's worth a try.
3. It's definitely better, apart from a slightly "dirty" looking patch near the leading and trailing edge.
4. Sure. 

Cheers,
Vik

**Pull request merged**
