### PR TITLE
New interior textures2

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
New textures for:

- trim tab
- fibreglass texture to be seen from the holes of the speedbrake handle
- top of the vent
- three large screws in the panel

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
See https://github.com/viktorradnai/flightgear-ask21/issues/119 for more info

**Comment by ghost** [comment]
Very nice low-poly version for the trim tab!!!

**Comment by gilbertohasnofb** [comment]
@D-ECHO thanks! :smile: If the textures are fine you can merge this and then work on the 3D modelling later on

**Comment by ghost** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@D-ECHO Ok, so now most of the issues involve 3D modelling. In that case, I might start taking a look at the textures of the ASW28, but please let me know if I can be of any help here, ok?

**Comment by ghost** [comment]
Could you maybe add a red part for the rear canopy openers (and make the surrounding of the rear canopy opener placard red as well?)

**Comment by gilbertohasnofb** [comment]
@D-ECHO Sure, I can do that, but can you show me some photo of what you are talking about?

**Comment by ghost** [comment]
Unfortunately I can only find this (sim) one atm: http://www.aerosoft.de/shop-rd/bilder/screenshots/fsx/ask21-glider/ask21-glider-06.jpg

**Comment by gilbertohasnofb** [comment]
:+1:

**Pull request merged**
