### PR TITLE
Airspeed indicator updates

### PR DESCRIPTION
**Pull request by viktorradnai**
Redone ASI in km/h and added another ASI in knots.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Looks nice :D Could you maybe also add the winter logo from the knots variant to the kph variant?

**Comment by viktorradnai** [comment]
I can add the Winter logo but it would be helpful to see what picture you have used to create your improved vesion of the km/h ASI as well. Could you please add it here? The knots version is in the Inkscape source file as a layer.

**Comment by ghost** [comment]
I used this image:
Winter ASI

**Comment by ghost** [comment]
Though I don't like including these images to the .svg files, at least not in a public GPL version as we don't have the license rights to do so. If you want I can set up a private gitlab repository for source files

**Comment by viktorradnai** [comment]
We can at least have the photo of the knots version in Inkscape as I took that photo personally :)

**Comment by viktorradnai** [comment]
Can I merge this? There are a couple of small tweaks to do later anyway, such as making half of the needle black.

**Comment by ghost** [comment]
Done ;)

**Pull request merged**
