### PR TITLE
Make instruments selectable via livery

### PR DESCRIPTION
**Pull request by ghost**
I couldn't find good ft-Altimeter and kts-Airspeed Indicator for the moment, but these should do it till we have better ones

### CODE REVIEW

**Comment by viktorradnai** [comment]
I will change the dials for the existing ASI once I have a photo of a spiral one in knots. It's probably the same just the numbers are different. I'll also look for a better altimeter.

**Comment by ghost** [comment]
Fine :)


Am 06.01.2017 um 23:18 schrieb Viktor Radnai:

**Review by viktorradnai — APPROVED** [review]
I have added a bunch of new changes, please review them and merge if you're happy with them

**Comment by gilbertohasnofb** [comment]
@viktorradnai perhaps a better way of handling this would be to allow the user to select the units in the aircraft menu regardless of the livery. Some users could potentially be quite confused if the instrumentation changes with livery, not realizing what is triggering the change.

**Pull request merged**
