### PR TITLE
Add (currently not 100% working) window keyboard code, improve tail s…

### PR DESCRIPTION
**Pull request by ghost**
…ection, fix rudder uvmap

### CODE REVIEW

**Comment by ghost** [comment]
@viktorradnai or @gilbertohasnofb would you mind having a look at the keyboard binding? It seems like it's not working

**Review by viktorradnai — APPROVED** [review]
Looks good to me, I will try to do something with the keyboard shortcut.

**Comment by ghost** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@D-ECHO @viktorradnai after much troubleshooting I found out that for some reason the key `d` (key number 100) is defective in FlightGear and don't behave as expected for some unknown reason! Changing the shortcut to _any_ other key fixes it, as @D-ECHO 's code was absolutely fine. I have set it now to `D` and it works perfectly, and I have also used the same shortcut to the instructor window. IMO this PR is ready to be merged.

**Comment by ghost** [comment]
Works for me not, thanks :+1:

**Comment by gilbertohasnofb** [comment]
Great :+1: 

So now I will get on with those texture :smile:

**Pull request merged**
