### PR TITLE
Regenerate Color Cubemap

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
After this PR is merged, I think we're ready for pushing V3.0 to FGADDON! If there are any major problems to solve until then, please yell ;)

**Comment by gilbertohasnofb** [comment]
Checking now

**Comment by gilbertohasnofb** [comment]
Ok, I took a look at it and here is my feedback:

- the reflections seem to still be flipped (horizontally inverted). Things on the left side of the cockpit are reflected on the right side of the canopy and vice-versa. Also, the size of some of the reflections are just gigantic, see for instance the AIS as seen from the instructor's point of view:

fgfs-screen-001

fgfs-screen-002

- from the instructor's default point of view, we can't see the hook placard. Perhaps move it like in the second image below:





- talking of placards, the co-pilot airbrake placards have some space between them which look really good (similar to photos I have seen), but the pilot placards are side by side. Wouldn't it look better if they were positioned similarly as the instructor's?

fgfs-screen-003

fgfs-screen-004

**Comment by gilbertohasnofb** [comment]
> After this PR is merged, I think we're ready for pushing V3.0 to FGADDON! If there are any major problems to solve until then, please yell ;)

@D-ECHO I am all for it as well! But perhaps we could consider implementing the trim reference tab so that the cockpit becomes 100% functional, what do you think?

**Comment by ghost** [comment]
1. Are you sure it isn't correct that the reflections show up on the other side, talking of how light falls and reflection works?
2. Are you sure the scale isn't possible due to curved glass?
3. Will correct rear hook placard
4. The front airbrake placards don't have space between, see: https://www.alexander-schleicher.de/wp-content/uploads/2015/03/21-Cockpit-002.jpg

**Comment by ghost** [comment]
3. done

**Comment by ghost** [comment]
About the trim reference, I'll try to do this for next version, as V3.0 is scheduled for tomorrow

**Comment by ghost** [comment]
Just re-checked, the cubemap should be correct (positive-y e.g. goes to right just like in the c172)

**Comment by gilbertohasnofb** [comment]
1. See this (look at the red knob on the right or the yellow on the left, no inverted reflections here):



> Just re-checked, the cubemap should be correct (positive-y e.g. goes to right just like in the c172)

So then the c172p is also wrong I suppose

2. I don't know, it just looks outrageously large
3. Perfect, thanks! :+1:
4. Ok, so let's just leave it as it is :+1:

> V3.0 is scheduled for tomorrow

What do you mean by that? Can we merge into FGADDON only at specific dates??

**Comment by ghost** [comment]
1. Well, okay, then I change it ;)
2. I don't as well

And well, it's not that we only can on specific days but I usually set milestones at some day every 1/2 month(s), but you're probably right, it's possible to move them, however I'm not going to have much time in the next weeks as well, so I think it's good to push version 3.0 now and care about trim afterwards, otherwise we have nothing to do for 4.0 ;)

**Comment by gilbertohasnofb** [comment]
@D-ECHO Sorry for my delay. I took a look at this and everything is looking better. If you really want to release this into FGADDON today then go ahead and merge this PR, but I still think that we need to solve somethings related to this PR:

- I think the hook release placard is now too far away from the lever in the instructor cockpit. See image below.

- there are still some issues with the cubemap, in particular from the instructor's view. Take a look at `Models/Effects/cubemap_rear_color/0002.png`, you will see that the altimeter is upside down (the zero should be on top of the cockpit -- i.e. left of the image file -- instead of being on the bottom -- i.e. right of the image file). Also, the vario units in the cubemap do not match the cockpit ones (cockpit is in knots, the reflection is in m/s).

fgfs-screen-001

> otherwise we have nothing to do for 4.0 ;)

That's true, but once this plane is pretty much complete we could move on to another glider, perhaps the ASW28! :wink:

**Comment by ghost** [comment]
About the wrong 0002.png: I've swapped left/right to make the altimeter appear on the left side, probably this leads to the problem.

**Comment by gilbertohasnofb** [comment]
>  I've swapped left/right to make the altimeter appear on the left side, probably this leads to the problem.

@D-ECHO did you push it yet?

**Comment by ghost** [comment]
To FGADDON?


Am 25.03.2017 um 18:24 schrieb Gilberto Agostinho:

**Comment by gilbertohasnofb** [comment]
No, if you push the commit modifying `0002.png`

**Comment by gilbertohasnofb** [comment]
You wrote:

> About the wrong 0002.png: I've swapped left/right to make the altimeter appear on the left side, probably this leads to the problem.

But I don't see any modifications here yet

**Comment by ghost** [comment]
@gilbertohasnofb After you said that the sides were wrong, I pushed commit 6f90e04 which swapped the sides, but a side effect seems to be the upside-down

**Comment by gilbertohasnofb** [comment]
@D-ECHO I think there might be some issues on how FG handles these reflections to be honest. But anyway, what I was pointing out is that the instruments in the `0002.png` file are completely different than the instruments in the cockpit, regardless of being upside down or not. Take a look at the altimeter in these images, the first image is a cropped and rotated version of `0002.png` and the second is just a screenshot:



fgfs-screen-001

Notice how the altimeters are completely different, one having the 0 in the bottom the other on the top, the vario gauge also has different scales (one is in m/s the other in knots). From the instructor's point of view this reflection is very clear so I think we should make sure it matches the current cockpit.

> I think the hook release placard is now too far away from the lever in the instructor cockpit. See image below.

Do you think you could also take a look at this, see the image in this post here https://github.com/viktorradnai/flightgear-ask21/pull/118#issuecomment-289211503 and look for the pink rectangle to see what I meant

**Comment by viktorradnai** [comment]
Before you guys spend way too much time on this, please remember that the
cockpit 3D model has a bunch of errors that need to be fixed.

**Comment by gilbertohasnofb** [comment]
@viktorradnai which errors?
@D-ECHO if recreating these cube maps is too much trouble (in case there would be any major modifications to the cockpit in the near future), then I suppose that we could just move the instructor hook placard and merge this

**Comment by viktorradnai** [comment]
@gilbertohasnofb the cockpit model has the a bunch of things that are wrong still, I've summarised them in #119.

**Comment by ghost** [comment]
@gilbertohasnofb that's because some livery have special instruments (e.g. the british ones have ft/s instead of m/s)

Please let's just merge this, a completely remodelled interior and fuselage is close to be finished, all things needed will be done after that.

**Comment by gilbertohasnofb** [comment]
@D-ECHO Fine, but would you mind moving that placard, please? Pink rectangle here: https://github.com/viktorradnai/flightgear-ask21/pull/118#issuecomment-289211503

**Comment by ghost** [comment]
Will be done with new interior model


Am 27.03.2017 um 18:29 schrieb Gilberto Agostinho:

**Comment by gilbertohasnofb** [comment]
> Will be done with new interior model

Sorry for the insistence, but is it really that much trouble to move it now since we already touched this in this PR?

**Comment by ghost** [comment]
Sorry  @gilbertohasnofb for the resistance :P but I don't see a point in loading up a (now) deprecated interior model and changing something that will 100% sure be overridden by changes coming very soon. If you (understandably) would like to keep the master branch clean/correct, we can keep this PR open and I will push the new modelled interior into this branch (newcubemap)

**Pull request merged**
