### PR TITLE
New GMeter texture with red/yellow markings

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@D-ECHO Would you mind applying some transparency to the yellow and red arcs you added? Right now it is not fitting very well with the gauge IMO. Just make the colours more intense (more saturated) then use a tad bit lower transparency, so that some of the metal texture comes through. What do you think?

**Comment by ghost** [comment]
@gilbertohasnofb I'm not 100% sure what you mean, is it like this?
screenshot_20171225_185513

**Comment by gilbertohasnofb** [comment]
Yes! That looks much better, because the colours are not full solid. But when you make that layer a bit transparent, the colours fade away a bit so you can compensate their saturation to your liking. But it's looking good right now!

And oh, one more thing I just noticed: it seems that the new layer is larger than the canvas size and so this newly exported png file is having some transparent pixels on the right and on the bottom (see the dashed lines in the image you just posted). You always need to either resize the layers to the image size or alternatively you can flatten the image just before exporting.

**Comment by ghost** [comment]
Should be fine now :D

**Review by viktorradnai — APPROVED** [review]
Looks nice.

**Comment by gilbertohasnofb** [comment]
Very nice, thanks!

**Pull request merged**
