### PR TITLE
New instrument textures

### LINKED ISSUE #96: improve instrument textures

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Closes #96

Better textures for all instruments

### CODE REVIEW

**Comment by ghost** [comment]
Will look at this now

**Comment by gilbertohasnofb** [comment]
@D-ECHO just a sec, one more commit to solve the conflict

**Comment by gilbertohasnofb** [comment]
@D-ECHO Ok, now it should be all good, I think the conflict about the SC7 is solved now

**Comment by gilbertohasnofb** [comment]
@D-ECHO Thanks!

**Comment by ghost** [comment]
Can be deleted?

**Pull request merged**
