### PR TITLE
FDM tweak and reflectivity / shininess

### PR DESCRIPTION
**Pull request by viktorradnai**
This attempts to fix the following:
#83 
#55

### CODE REVIEW

**Comment by viktorradnai** [comment]
Please check the handling of the glider as I've pretty much re-done the glide angle, stall and elevator authority from scratch. It may need further tweaking but it appears to better match the polar curve at higher speeds:
ask21_polar

**Comment by gilbertohasnofb** [comment]
I think it would be better if @D-ECHO reviews this as I am not familiar with the glider at all yet, so far I just made textures for it but I basically didn't take it out of the ground :wink:

**Comment by viktorradnai** [comment]
Actually there is one problem with the new FDM. The glider flies too nose high. When aerotowing at around 55-60 knots if I fly in the normal tow position placing the tug just above the horizon then it would get hidden by top of the instrument panel / nose. I'm trying to fix this but FDM changes are pretty tedious and I won't have time until this evening at best.

**Review by ghost — APPROVED** [review]
-the effect looks really good!!
-the FDM matches best glide very well, though the vertical speed should be higher when flying at speeds like 140kph (only 0.9-1 currently instead of 1.6) -> all in all amazing job!!!!

**Comment by ghost** [comment]
@viktorradnai Also I think the spoilers are not effective enough :D

**Comment by viktorradnai** [comment]
@D-ECHO yes, I'm aware of that and will do my best to address it. BTW, I think the spoilers (airbrakes) are too small on the 3D model as well, the real ones come out higher. Also the sides (at least the front, not sure about the back) are painted orange for better visibiility. I've been meaning to flag this up as well, but kept forgetting :)

**Pull request merged**
