### PR TITLE
Rearranged panels and added switches

### PR DESCRIPTION
**Pull request by viktorradnai**
This PR is against the newint branch as it depends on the changes in there. I have rearranged the instrument panel to better reflect the trends our club's gliders have. For the front panel this means ASI and altimeter on the left, varios, accelerometers on the right, radio almost at the bottom of the panel. There is always a master switch and at least oanother switch for the turn and slip which is normally kept off to save battery. On the rear the compass seems to be on the left, ASI and altimeter on the left as well, and everything else wherever there is room left :)

I couldn't figure out the immat.xml to move the callsign label without breaking the animation. Can this be made part of the instrument panel?

@D-ECHO Could you please move the callsign label somewhere below the screw on the front panel, and add another callsign label to the instructor panel just below the radio?

BTW, talking about the radio, it's fairly common in our club's gliders that the instructor has a slave control unit for the radio in the back so I added the radio there as well.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Looks excellent

**Comment by ghost** [comment]
@gilbertohasnofb would you mind adding a better (more metallish :D) switch texture, maybe based on this: http://imgproc.airliners.net/photos/airliners/5/8/9/1057985.jpg?v=v40

**Comment by gilbertohasnofb** [comment]
@D-ECHO :+1:

**Comment by gilbertohasnofb** [comment]
@D-ECHO done, please see `panel.png` in `newint`. I used the switch texture from the c172p which looks quite nice. There is a texture for the base of the switch as well as for the switch itself (take a look at the UV-mapping in the c172p if you need)

**Pull request merged**
