### PR TITLE
Various fixes and improvements by Herbert Wagner

### PR DESCRIPTION
**Pull request by ghost**
I have incorporated some changes Herbert Wagner sent me via Email, please have a look

### CODE REVIEW

**Comment by ghost** [comment]
@HerbyW

**Comment by viktorradnai** [comment]
Hi @HerbyW, thanks for these improvements. I have to try to live with them for a bit longer but after trying them out, I already have the some comments. I think it's probably better to state them here than scatter them around the code in the form of a review.

First, there is a serious bug, where after landing the glider will accelerate backwards if the airbrake is open but the brakes aren't on. No idea what causes this, although I should add that I landed on "terrain" rather than an airfield. 

Second, I wouldn't enable pilot visibility inside the cockpit by default. When you do this, you can no longer see the position of the controls (stick, airbrake, trim lever, rudders) which @D-ECHO has modelled and animated quite well.

I haven't really played much with the wind compass. I didn't really want to add too many fancy instruments to the ASK21 cockpit as most of them have pretty basic instruments (since they are mostly used for flight training or perhaps aerobatics). But since the compass is an option you can toggle, I'm happy to have it. Although you could consider having a "basic" and an "advanced" panel instead of overlaying new instruments on top of the basic panel.

I have changed back the view position to be 10cm higher. This enables me to see the tug aircraft properly when aerotowing at 60 knots, as it is the case in real life. With the old view position the tug would disappear from view when its wheels were about to touch the horizon.

**Comment by viktorradnai** [comment]
Regarding the stall behaviour, I'm not sure what to think. Your modified polar curve appears correct, which is impressive as it took me a lot of fiddling to get it close enough previously. Using Nasal to overcome the limitations of YASim is a dirty hack, but I'm OK with it if there is no other way. But I feel that the implementation has a fundamental problem. 

Stall (both the reduced lift and the increased drag) is a function of the angle of attack, not speed. If you stall the glider using straight and level flight, by gradually moving the stick to the backstop to keep the nose from dropping, the glider will start to descend. But once you centre the stick and the nose goes down, the glider should almost immediately unstall as you have reduced the AoA. But the Nasal stall code does not take this into account and continues to reduce lift and increase drag until the speed picks up again. 

I only tested it for maybe an hour or two last night but the behaviour feels "wrong" somehow. Several times I found myself in deep trouble while hill soaring because of this. I attempted to fly over some trees but accidentally allowed the airspeed to drop. I lowered the nose slightly but it was too late. The stall code kicked in and the glider started to rapidly descend into the trees. I put the stick forward a lot more to get the nose down, but the rapid descent continued even as the glider accelerated with the nose low. I just sat there helplessly while losing height at an alarming rate and most of the time I crashed into terrain before I could get the speed up. I think the height loss would have been close to 100ft which is probably 3 times what it should be.

I also think that the stall happens too easily and without warning. It must be that once the speed goes below 40 knots, the stall code kicks in and reduces speed further. Normally I would expect the nose to drop before that happens, unless you apply full up elevator.

**Comment by viktorradnai** [comment]
I have asked on flightgear-devel to see if anyone can help us implement mushing stall using YASim, but haven't received a reply yet. Feel free to chip in or try to ask on the forums. I still think that using Nasal to do FDM type stuff is the path to the dark side :)

**Comment by viktorradnai** [comment]
Hi again, I've now started a discussion on this on flightgear-devel. I have also found this video that shows some stall exercises starting after the aerotow release around 5:50: https://www.youtube.com/watch?v=pSK5quxFWnk

Surprisingly enough, the variometer does not really go down much even when the glider stalls with the nose up high. I need to try a proper mush next time I fly an ASK21 to see what the vario does if the mushing condition is maintained for a few seconds.

**Comment by ghost** [comment]
I'll close this PR for now so it doesn't get merged, some significant changes and improvements are soon coming to the herby branch

**Comment by viktorradnai** [comment]
@D-ECHO this looks pretty good, lot of work has gone into it and the Mi variant is a welcome addition too. On the other hand, could you please avoid such large pull requests with multiple features in the future? I didn't merge it because I didn't have time to properly review everything that has gone into it. I was going to do it eventually but now it's too late.

**Comment by ghost** [comment]
Okay, sorry for this

**Comment by viktorradnai** [comment]
No worries :)

**Pull request merged**
