### PR TITLE
Improvements to G-CJWD and change in reflectivity

### PR DESCRIPTION
**Pull request by viktorradnai**
The paintkit is a bit of a mess now but I didn't want to merge down all the text layers until I'm done with G-CKEJ as well.

### CODE REVIEW

**Comment by viktorradnai** [comment]
@D-ECHO FYI the texture on the rudder is scaled too much when viewed from the left, I had to make that letter a little smaller to compensate. The font is Arial for the fuselage and I think it's Arial Narrow for the rest. I didn't have Arial Narrow handy so I just stretched the text a little.

**Review by ghost — CHANGES_REQUESTED** [review]
-I will fix the problem with the uvmap, but please make the text on the livery equal big, so we don't have problems later
-somehow my flightgear now dsplays the whole model grey and says it can't find the effect, I'm going to investigate the reason ;) maybe something needs to be changed to work for all systems

**Comment by ghost** [comment]
Please have a look whether it still works for you now, I changed some configurial things

**Comment by ghost** [comment]
Btw, I saw you removed the reflect-type 2 part, don't you like it? It's actually for just this defined, highly reflective surfaces which are white
-> if the reflection is too much, it can be changed by reflection-correction

**Comment by viktorradnai** [comment]
The effect still works for me after your changes. 

I found that the fuselage was way too reflective, it looked like highly polished metal. Using the same effect as for the wing gives more consistent results.

**Comment by ghost** [comment]
@viktorradnai Okay, fine about the effect (for the moment ;P)
I've corrected the rudder uv-map, the changed .png can be securely overwritten

**Comment by ghost** [comment]
@viktorradnai do the people at your club never polish  the ASK21 good?

**Comment by ghost** [comment]
@viktorradnai Do you want to correct the livery or shall I?

**Comment by viktorradnai** [comment]
I'll do the correction, I have it open in Gimp still.

**Comment by viktorradnai** [comment]
@D-ECHO I've further improved the liveries of both JWD and KEJ. The font used seems tricky.The reg uses some variant of Helvetica I think, the BGA callsign (the three letters on the tail) are something similar but a little bit different. Be careful if you need to edit this, some of the letters come from a different font :) Maybe best to just squash down the layers and call it done.

**Comment by viktorradnai** [comment]
Regarding fuselage shininess: this is the UK and these aircraft get rained on at least once or twice every month. They are shiny but not like glass or metal :)

**Review by ghost — APPROVED** [review]
Fine now ;)

**Pull request merged**
