### PR TITLE
New interior and many more things

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@D-ECHO I think you forgot about this issue here:

fgfs-screen-001

fgfs-screen-002

These circled parts have carpet/floor textures, but they should all be metallic. If you need to apply a metallic texture to any part of the cockpit, I suggest mapping it to this area here:

parts

**Comment by ghost** [comment]
1. the block behind the copilot has that greenish glass-fibre look: 
https://www.alexander-schleicher.de/wp-content/uploads/2015/03/21-Cockpit-006.jpg
2. at least in our ASK21 those armrests are made of black fabric, close to what we have as a carpet texture

**Comment by gilbertohasnofb** [comment]
But then I can create textures for that! For 1., I can work on it. For 2., can you show me pictures of that?? This picture here for instance show no such thing:

http://www.hca-online.de/attachments/Image/SIMG0075_klein.jpg?template=generic

**Comment by ghost** [comment]
Unfortunately it seems like only we use it, so theres no picture on the net, maybe we can make it optional by livery later :D

**Comment by gilbertohasnofb** [comment]
One more thing, shouldn't the back of the canopy placards use the texture in the bottom right corner of `parts.png`? See: 

fgfs-screen-005

**Comment by gilbertohasnofb** [comment]
> Unfortunately it seems like only we use it

In that case, perhaps we should remove it from the model?

**Comment by gilbertohasnofb** [comment]
@D-ECHO Ok, just pushed some new textures:

parts

The upper red square is for the back of the instructor's seat. If you need more of the yellow carbon fibre texture, use the purple rectangle area. The green square shows the texture for the cushion behind the instructor's head. 

And take a look on what I wrote above about the back of the placards, ok?

**Comment by ghost** [comment]
Please have a look. And please note that it is more greenish IRL (see photo)
About the door openers, I have added it to the rear ones but I'm not sure whether it's also used for the front ones, as these shouldn't be marked red (they are not emergency canopy jettison handles!)

**Comment by gilbertohasnofb** [comment]
> Please have a look

Looks way better to me!

> And please note that it is more greenish IRL (see photo)

I think that's because the carbon fibre in that model is more greenish, isn't it? Shouldn't the colour be consistent with the rest of the plane? Else I can change that, of course.

What needs to be done still:

* decide this green/yellow colour thing
* ~~apply new texture to the back of the placards~~ done!
* if you really want to have those cushions, I would really like the texture to be different than the carpet one, to my eyes it doesn't look good at all. Perhaps you could then use the full blue texture of the instructor's head support?
* ~~the screw in the image below is still a bit cut on the top:~~ done!

fgfs-screen-001

**Comment by ghost** [comment]
See 6d83fb6 for the screw

**Comment by ghost** [comment]
I think all of the glass fibre parts are more greenish

**Comment by gilbertohasnofb** [comment]
@D-ECHO great! Almost there :1st_place_medal: So only the colour thing + the arm rests

**Comment by gilbertohasnofb** [comment]
I don't know, some models clearly have it quite green:



But the pictures @viktorradnai posted were very clearly yellow to me, see: https://drive.google.com/drive/folders/0BxVWkln4EgdVODV5SXJjRDh5STg

**Comment by ghost** [comment]
I think that's just a lighting thing

**Comment by ghost** [comment]
Funny thing: I just saw in a TV emission where our ASK21 was shown that the black fabric isn't always on, in that scene it was off :D so we can make it optional

**Comment by ghost** [comment]
See 9a5b496f3e0b19ec15ec935a5da57ed75b7691ea

**Comment by gilbertohasnofb** [comment]
@D-ECHO this is looking really good :clap::clap::clap: 

I like the idea of making the armrests switchable, but I still don't like the carpet texture being used for it at all. I will push a new texture for it, is that ok with you?

> I think that's just a lighting thing

I am really not sure about this one! I will probably tweak a little bit the colour, but I think we should stick with one reference, and for me I use Viktor's photos for the textures.

**Comment by gilbertohasnofb** [comment]
@D-ECHO Ok, just pushed one commit. Fiberglass parts are greener, darker and dirtier (they look much more like the image above) and I added a black texture for the cushions, could you UV-map it? The new texture is the black square just above the trim down placard (bottom right).

I also noticed that the hole for the instructor's speedbrake does not show the green fiberglass texture like in the pilot's seat.

**Comment by ghost** [comment]
1. done :D thanks!
2. are you show it isn't just blocked by the actual speedbrake operator bar from your view? 
fgfs-screen-265

**Comment by gilbertohasnofb** [comment]
Thanks for applying that texture to the armrest, it looks much better!

> are you show it isn't just blocked by the actual speedbrake operator bar from your view?

Well, as far as I can tell there should be no difference between the passenger and the instructor's speedbrake. See how the mechanism is identical to the passenger and how the green carbon fibre material is behind the whole system, so if you can see it from the passenger's point of view then you should also see if from the instructor's, right?

**Comment by ghost** [comment]
Okay, that's it: From the photo it seems our bar is much too thick, that's why it blocks too much of the view

**Comment by ghost** [comment]
Please pull and try again

**Comment by gilbertohasnofb** [comment]
@D-ECHO :clap: :clap: :clap: great work, this interior is looking excellent!

**Comment by ghost** [comment]
Thanks!


Am 21.04.2017 um 13:20 schrieb Gilberto Agostinho:

**Pull request merged**
