### PR TITLE
New seat texture, copilot visible according to weight, move panel immat

### PR DESCRIPTION
**Pull request by ghost**
The copilot is not really working, he is only showing from 80-99 lbs, could you check this?

### CODE REVIEW

**Comment by ghost** [comment]
Though it's not the fine way, the immat is now less "gappy" due to the planes overlapping :D

**Comment by ghost** [comment]
I fixed a small issue in interior glass and added the (lost?) exterior glass

**Comment by ghost** [comment]
Could review whether the rudder pedal mechanic is correct? I could only guess it...

**Comment by viktorradnai** [comment]
I think the rear rudder pedals are spaced further apart, and the front seat pan might be more narrow (and not blue) when viewed from the rear seat, but I could be wrong. One thing I'm sure about though -- when dumping the front canopy, the instrument panel will stay attached to the glider. It has way too many cables and tubes connected to just fly off like that, not to mention the weight of it.

**Pull request merged**
